import { useState } from 'react';
import { Sparkles, Copy, Check, Info } from 'lucide-react';
import { useAppData } from '../hooks/useAppData';
import { Card, EmptyState, ErrorState, Skeleton } from './ui';
import { riskStyle } from '../utils/format';
import AiTelemetryPanel from './AiTelemetryPanel';

const FAILURE_TEXT = {
  timeout: 'the AI provider timed out',
  http_error: 'the AI provider returned an error',
  network: 'the AI provider could not be reached',
  invalid_output: 'the AI reply failed validation',
};

function CopyButton({ text }) {
  const [done, setDone] = useState(false);
  const copy = async () => {
    try { await navigator.clipboard.writeText(text); setDone(true); setTimeout(() => setDone(false), 2000); } catch { /* clipboard blocked: user can still select the text */ }
  };
  return (
    <button onClick={copy} className="inline-flex items-center gap-1.5 rounded-md bg-white px-2.5 py-1 text-xs font-medium text-slate-700 ring-1 ring-slate-300 hover:bg-slate-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-field-600">
      {done ? <Check className="h-3.5 w-3.5 text-emerald-700" aria-hidden="true" /> : <Copy className="h-3.5 w-3.5" aria-hidden="true" />}
      <span aria-live="polite">{done ? 'Copied' : 'Copy message'}</span>
    </button>
  );
}

const SourceChip = ({ insight }) => {
  const ai = insight.source === 'claude';
  return (
    <span className={`rounded px-2 py-0.5 text-xs font-medium ${ai ? 'bg-field-50 text-field-700 ring-1 ring-inset ring-field-600/20' : 'bg-slate-100 text-slate-700'}`}>
      {ai ? 'Generated by AI' : 'Deterministic fallback'}
    </span>
  );
};

function Analysis({ insight }) {
  const sec = insight.sections;
  const level = insight.urgencyLevel;
  const style = riskStyle(level);
  const fallback = insight.source !== 'claude';
  const why = insight.error && FAILURE_TEXT[insight.failureType];
  return (
    <div className="space-y-4">
      <div className={`rounded-md border p-4 ${level ? style.panel : 'border-slate-200 bg-slate-50'}`}>
        {level && <p className={`mb-1 text-xs font-bold ${style.text}`}>URGENCY: {level}</p>}
        <p className="text-base font-semibold leading-snug text-ink">{sec.summary || 'No summary was provided.'}</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <section aria-labelledby="ai-why">
          <h3 id="ai-why" className="text-sm font-semibold text-slate-800">Why this shipment is at risk</h3>
          <p className="mt-1 max-w-prose text-sm leading-relaxed text-slate-700">{sec.risk || 'Not provided.'}</p>
        </section>
        <section aria-labelledby="ai-action" className="rounded-md bg-field-50 p-3">
          <h3 id="ai-action" className="text-sm font-semibold text-field-700">What the distributor should do now</h3>
          <p className="mt-1 max-w-prose text-sm leading-relaxed text-slate-800">{sec.action || 'Not provided.'}</p>
        </section>
      </div>

      {sec.retailer && (
        <section aria-labelledby="ai-retailer" className="rounded-md border border-slate-200 p-3">
          <div className="flex items-center justify-between gap-2">
            <h3 id="ai-retailer" className="text-sm font-semibold text-slate-800">Message for retailers</h3>
            <CopyButton text={sec.retailer} />
          </div>
          <blockquote className="mt-2 border-l-4 border-field-600 pl-3 text-sm leading-relaxed text-slate-800">{sec.retailer}</blockquote>
        </section>
      )}

      {fallback && (
        <p className="flex items-start gap-2 rounded-md bg-slate-50 p-3 text-xs leading-relaxed text-slate-600">
          <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden="true" />
          <span>
            {insight.error === 'AI key not configured'
              ? 'No AI key is configured on the server, so this analysis comes from the built-in template.'
              : `The AI service did not return a usable answer (${why || 'an error occurred'}), so this analysis comes from the built-in template.`}
            {' '}Shelf life, risk and prices are unaffected: they are always calculated by the deterministic engines.
          </span>
        </p>
      )}

      <p className="text-xs text-slate-500">
        {insight.model ? `Model ${insight.model}` : 'No model call'}
        {insight.promptVersion ? `, prompt ${insight.promptVersion}` : ''}
        {insight.latencyMs != null && insight.source === 'claude' ? `, ${insight.latencyMs} ms` : ''}
        {insight.attempts > 1 ? `, ${insight.attempts} attempts` : ''}
        {insight.time ? `, generated ${insight.time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}` : ''}
      </p>
    </div>
  );
}

export default function InsightCard() {
  const { insight, shipment, telemetry, errors, refreshAll } = useAppData();
  let body;
  if (errors.insight) body = <ErrorState title="AI analysis unavailable" error={errors.insight} onRetry={refreshAll} />;
  else if (telemetry === null) body = <Skeleton className="h-24 w-full" />;
  else if (!insight) body = <EmptyState title="No AI analysis yet" hint={shipment?.riskLevel === 'LOW' ? 'Analysis is generated by the backend when risk rises above LOW.' : 'Waiting for the backend to generate analysis.'} icon={Sparkles} />;
  else if (insight.sections) body = <Analysis insight={insight} />;
  else body = <p className="max-w-prose whitespace-pre-line text-sm leading-relaxed text-slate-800">{insight.text}</p>;
  return (
    <Card title="AI cold-chain analysis" icon={Sparkles} action={insight?.source && <SourceChip insight={insight} />}>
      {body}
      <AiTelemetryPanel />
    </Card>
  );
}
